# Generated by Django 4.2.18 on 2025-02-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='starttime',
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
