# Generated by Django 4.2.18 on 2025-02-20 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticeboard', '0007_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='starttime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='event',
            name='bookable_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=15)),
                ('is_facilitator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticeboard.communityuser')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
